### ISSUE TITLE
How to use reactdns in a waiting (sync) mode?

### ISSUE THREAD

**Issue by webaddicto** [reactphp/dns#192]
Hello team,

Awesome job with reactphp and in particular (for my use case) reactdns!

I have two questions:

1) If I get TYPE_A records of an array list of domains such as in the example [02-concurrent.php](https://github.com/reactphp/dns/blob/master/examples/02-concurrent.php) there is no way to have a sort of sleep every say 10 events, it scans all domains in parallel. How can I set a sleep of 1 second every 10 requests or limit concurrent requests to 10?

2) How can I use your reactdns for single DNS queries (not concurrent/async) and wait for the results before moving to the next code/function? An example I'd like to achieve is like this:

```
$details = array();

$domain = "google.com";

$type_a = $resolver->resolveAll($domain, Message::TYPE_A);

if(!isset($type_a['exceptionMessage'])) {
    foreach($type_a as $record)  {
        $details[$domain]['ips'][] = $record->ip;
    }
} else {
    $details[$domain]['exception'] = $type_a['exceptionMessage']; // DNS query for example.com (A) did not return a valid answer (NOERROR / NODATA)
}

print_r($details);
```

Thank you!

**Comment by WyriHaximus** [comment]
Hey @webaddicto, have a look at https://github.com/reactphp/async#async that should help you do this. You're code will become something like:

```php
$details = array();

$domain = "google.com";

$type_a = await($resolver->resolveAll($domain, Message::TYPE_A));

if(!isset($type_a['exceptionMessage'])) {
    foreach($type_a as $record)  {
        $details[$domain]['ips'][] = $record->ip;
    }
} else {
    $details[$domain]['exception'] = $type_a['exceptionMessage']; // DNS query for example.com (A) did not return a valid answer (NOERROR / NODATA)
}

print_r($details);
```

**Comment by SimonFrings** [comment]
Thanks @webaddicto :+1: 

1. It seems like `sleep()` is not exactly the thing you're looking for. You can take a look at @clue's answer in [reactphp/dns#152](https://github.com/reactphp/dns/issues/152#issuecomment-536295343), this should fit your needs.

2. Like @WyriHaximus this one sounds a lot like you want to use `await()`. For that you can take a look at https://github.com/reactphp/async. Additionally your `$type_a` gets an array after awaiting (in @WyriHaximus  example) and because of that you need to work with `try{} catch{}` afterwards instead of your `if{} else{}`.

I hope this helps :+1:

**Comment by clue** [comment]
I believe this has been answered, so I'm closing this for now. Please come back with more details if this problem persists and we can always reopen this :+1:
