### ISSUE TITLE
How to store data in array when doing resolveAll()?

### ISSUE THREAD

**Issue by webaddicto** [reactphp/dns#193]
Just another question (I'm a newbie here):

How can I store the returned data in an array? Example:

```
                $result = array();

		foreach($domains as $domain) {
	            $resolver->resolveAll($domain, Message::TYPE_A)->then(function (array $ips) use ($domain)  {
		        echo $domain." -> ".implode(', ', $ips)."\n";
		        $result[$domain] = implode(', ', $ips);
                    }, function (Exception $e) use ($domain, $result) {
		        echo $domain." -> ".$e->getMessage()."\n";
		        $result[$domain] = $e->getMessage();
                    });
		}
		
		print_r($result);
```

Thank you!

**Comment by SimonFrings** [comment]
@webaddicto Thanks for bringing this up :+1:

In your example you're doing something asynchronous but it looks like you want it to be synchronous. When you call your `resolveAll()` it can take a while until the promise actually resolves. This is where the asynchronous execution comes into play. While waiting for the promise to resolve, your `foreach()` is already continuing the next iteration until it is finished.

And right there's the problem:
Your `foreach()` finishes before the promises can resolve (because they take a little while). This leads to your `$result` being printed before it receives any values, thus it's empty. After that the promises resolve but nothing will happen because you already printed your `$result`.

You can take a look at the last two examples inside the [reactphp/async#async](https://github.com/reactphp/async#async) chapter. The first one is very similar to your example with an `await()` inside the `foreach()`. The second example shows how you can "await" multiple promises by using a single [await()](https://github.com/reactphp/async#await) together with Promise-based primitives.

I hope this helps, if you have any more questions let me know :+1:

**Comment by clue** [comment]
I believe this has been answered, so I'm closing this for now. Please come back with more details if this problem persists and we can always reopen this :+1:
