### ISSUE TITLE
"DNS Request did not return valid answer." But seems it should work.

### ISSUE THREAD

**Issue by DangerLifter** [reactphp/dns#21]
If I try to resolve these domains:
http://qdedu.net/
http://ens.fr/
I got "DNS Request did not return valid answer" response. But browser correctly redirects from these domains to "www" versions of them

**Comment by clue** [comment]
Apparently both (naked) domains do not have any DNS entries and can in fact not be resolved.

This can easily be reproduced by trying to resolve via nslookup (or similar) locally:

```bash
$ nslookup qdedu.net 8.8.8.8
```

This means that this library returns the correct result.

Browsers usually have some heuristics to try different combinations in order to fix common typing and/or misconfiguration errors. In this case, you browser seems to automatically prepend the "www" subdomain in front of the FQDN. Both domains have valid DNS entries for these subdomains.

**Comment by DangerLifter** [comment]
Thanks for explanation. Will take a look at it.
