### ISSUE TITLE
DNS query for X failed: too many retries.

### ISSUE THREAD

**Issue by avg0043** [reactphp/dns#84]
I'm getting this Exception error message from file "/react/dns/src/Query/RetryExecutor.php":

> DNS query for X failed: too many retries

I'm using `8.8.8.8` dns server and my libraries version are:
"react/http-client": "0.4.17"
"react/dns":"0.4.11"

I have tried using [OpenDNS](https://www.opendns.com/setupguide/) (`208.67.222.222` and `208.67.220.220`) but the problems persists...

How can I solve this? Thanks.

**Comment by clue** [comment]
Thanks for reporting! Similar issues have been reported before and we're currently not aware of any such issues.

Have you tried the [search](https://github.com/reactphp/dns/search?q=%22too+many+retries%22&type=Issues&utf8=%E2%9C%93) and in particular seen https://github.com/reactphp/dns/issues/78#issuecomment-328324863?

**Comment by avg0043** [comment]
This error doesn't happen all the time, but generally yes. I'm using Ubuntu 16.04 but I have tried in another machine using Windows 10 system and the exception is thrown too..

**Comment by clue** [comment]
Have you checked out the above links?

> Here's what the "DNS query for www.google.com failed: too many retries" error basically means: This component sends a UDP message (DNS query) to your DNS server and waits for a reply. If no answer is received within 5s, it will send a new UDP message and then another one again if no answer is received. If an answer is received, it will verify the response message and resolve the promise. The error shows that no answer has been received.
>
> So this basically means that we did not receive a reply messageg from your DNS server. This could be due to a number of reasons and could very likely be not something this package has control over.

If this does not happen all the time, if may be due to the fact that your network drops certain packages. Can you try running this from another network / host?

**Comment by avg0043** [comment]
Now I can't test this from another network.. So if someone finds the solution, please share it.
I need to realize thousands of http requests.. Thanks!

**Comment by clue** [comment]
Unfortunately, we're currently unable to reproduce the problem you're seeing. Can you provide a gist for us to reproduce this?

**Comment by clue** [comment]
Closing this due to a lack of feedback, as we can not reproduce this. Please come back with more details if this problem persists and we can reopen this :+1:

**Comment by aikar** [comment]
If anyone comes across this in googling, One source of this issue is using Tcp Transport and getting a large response back for TXT records.

You pretty much must use Udp instead of Tcp for reliable answers.

**Comment by clue** [comment]
> If anyone comes across this in googling, One source of this issue is using Tcp Transport and getting a large response back for TXT records.
> 
> You pretty much must use Udp instead of Tcp for reliable answers.

@aikar Please note you're commenting on a ticket that is several years old and your description doesn't match with what's been described here so far. If you are experiencing any issues, I would ask you to create a new ticket so we can take a look at this specifically.

In particular, this ticket here deals with a pre-1.0 version that didn't fully support loading default DNS configuration, automatically selecting TCP and UDP transports and didn't fully report many of the underlying error conditions. All of this has improved significantly ever since, so I invite you to run your tests with up-to-date components and report back if this problem persists.

**Comment by aikar** [comment]
@clue I am very much aware how old this is, but this is what comes up when you google for this error, so i wanted to share a potential source of the issue for others having this problem and hitting a dead end. I am not trying to 'file a new issue'.

In my case i was not using the SelectiveTransportExecutor, as I am needing to use the executors directly, and needed to switch to using it, so im simply making sure anyone else who stumbles on this ticket gets the same solution.

And to add more follow up info - make sure your DNS resolver supports TCP mode. If your firewall is allowing UDP only, you will end up seeing this error. Remove  your Retry Executor to see what error is generating the retries.

**Comment by SimonFrings** [comment]
@aikar I think it's great to share your insights in this ticket in order to move forward in finding a solution, as this hasn't been completely resolved for those encountering this error message. It was also a bit difficult for me to see the relation to this ticket from your first comment, so thanks for the additional input.

We're still not able to reproduce this error message, so it is hard to say if you're suggested solutions will work, but I think it's a good starting point for those stuck with this error :+1:
